### ISSUE TITLE
Missing chemical information for gold standard BGCs

### ISSUE THREAD

**Issue by althonos** [Adapsyn/prism-4-paper#3]
Hi @skinnider,

The Zenodo data for the gold standard BGCs does not contain any metadata about the "true" compound produced by the BGCs apart from the names of the files. The scripts depend on a `/data/platinum/all_mols.txt` file that is missing from the repository, so it is not possible to run at the moment. Could you please share these files or indicate how to get them if they are available somewhere?

Thanks in advance.

**Comment by skinnider** [comment]
Sorry @althonos, not sure why this wasn't included! I believe the attached should be the correct file. 
[all_mols.txt](https://github.com/Adapsyn/prism-4-paper/files/14638001/all_mols.txt)

**Comment by althonos** [comment]
Thank you! I managed to get most of these from one of the supplementary tables from the paper but it is much more practical to have it like this :smiley:
